\-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
\--   at:        2025-04-29 17:44:52 CDT
\--   site:      Oracle Database 21c
\--   type:      Oracle Database 21c

\-- predefined type, no DDL - MDSYS.SDO\_GEOMETRY

\-- predefined type, no DDL - XMLTYPE

CREATE TABLE Batch
(
batch\_name                VARCHAR2 (255)  NOT NULL ,
experiment\_id             VARCHAR2 (255)  NOT NULL ,
batch\_description         VARCHAR2 (255) ,
num\_images                INTEGER ,
Plate\_assay\_plate\_barcode VARCHAR2 (255)  NOT NULL ,
Plate\_plate\_name          VARCHAR2 (255)  NOT NULL
)
;

ALTER TABLE Batch
ADD CONSTRAINT Batch\_PK PRIMARY KEY ( batch\_name ) ;

CREATE TABLE Experiment
(
experiment\_id       VARCHAR2 (255)  NOT NULL ,
plate\_map\_name      VARCHAR2 (255) ,
assay\_plate\_barcode VARCHAR2 (255) ,
perturbogen         VARCHAR2 (255) ,
cell\_type           VARCHAR2 (255) ,
timepoint           VARCHAR2 (255) ,
density             VARCHAR2 (255) ,
antibiotics         VARCHAR2 (255) ,
cell\_line           VARCHAR2 (255) ,
time\_delay          VARCHAR2 (255) ,
times\_imaged        INTEGER ,
anomaly             VARCHAR2 (255) ,
number\_of\_images    INTEGER
)
;

ALTER TABLE Experiment
ADD CONSTRAINT Experiment\_PK PRIMARY KEY ( experiment\_id ) ;

CREATE TABLE feature\_rankings
(
perturbation\_type    VARCHAR2 (255)  NOT NULL ,
cell\_region          VARCHAR2 (255) ,
feature              VARCHAR2 (255)  NOT NULL ,
channel              VARCHAR2 (255) ,
suffix               VARCHAR2 (255) ,
feature\_significance FLOAT ,
median               FLOAT ,
jcp2022\_id           VARCHAR2 (255)  NOT NULL ,
gene\_compound\_image  VARCHAR2 (255) ,
phenotypic\_activity  FLOAT ,
gene\_compound        VARCHAR2 (255)  NOT NULL ,
resources            VARCHAR2 (255)
)
;

ALTER TABLE feature\_rankings
ADD CONSTRAINT feature\_rankings\_pk PRIMARY KEY ( feature, jcp2022\_id, gene\_compound ) ;

CREATE TABLE feature\_rankings\_link
(
perturbation\_type     VARCHAR2 (255)  NOT NULL ,
jcp2022\_id            VARCHAR2 (255)  NOT NULL ,
metadata\_inchi        VARCHAR2 (255) ,
metadata\_ncbi\_gene\_id VARCHAR2 (255) ,
P2T\_broad\_sample      VARCHAR2 (255)  NOT NULL ,
P2T\_perturbogen       VARCHAR2 (255)  NOT NULL ,
P2T\_gene              VARCHAR2 (255)  NOT NULL
)
;

CREATE TABLE P2P
(
gene                        VARCHAR2 (255) ,
comparison\_type             VARCHAR2 (255)  NOT NULL ,
mean\_average\_precision      FLOAT ,
nlog10pvalue                FLOAT ,
corrected\_p\_value           FLOAT ,
nlog10correctedpvalue       FLOAT ,
above\_p\_threshold           VARCHAR2 (255) ,
above\_corrected\_p\_threshold VARCHAR2 (255) ,
comparison\_description      VARCHAR2 (255) ,
modality1                   VARCHAR2 (255)  NOT NULL ,
modality2                   VARCHAR2 (255) ,
modality1\_timepoint         VARCHAR2 (255) ,
modality2\_timepoint         VARCHAR2 (255) ,
cell                        VARCHAR2 (255) ,
pert\_time                   VARCHAR2 (255) ,
t\_test\_statistic            FLOAT ,
t\_test\_p\_value              FLOAT ,
fishers\_exact\_statistic     FLOAT ,
fishers\_exact\_pvalue        FLOAT ,
cosine\_sim                  FLOAT
)
;

ALTER TABLE P2P
ADD CONSTRAINT P2P\_PK PRIMARY KEY ( comparison\_type, modality1 ) ;

CREATE TABLE P2P\_Perturbagen\_link
(
comparison\_type              VARCHAR2 (255)  NOT NULL ,
modality1                    VARCHAR2 (255)  NOT NULL ,
metadata\_jcp2022             VARCHAR2 (255) ,
Perturbagen\_metadata\_jcp2022 VARCHAR2 (255)  NOT NULL
)
;

ALTER TABLE P2P\_Perturbagen\_link
ADD CONSTRAINT P2P\_Perturbogen\_PK PRIMARY KEY ( comparison\_type, modality1 ) ;

CREATE TABLE P2T
(
broad\_sample    VARCHAR2 (255)  NOT NULL ,
inchikey        VARCHAR2 (255) ,
pert\_name       VARCHAR2 (255) ,
pubchem\_cid     VARCHAR2 (255) ,
perturbagen     VARCHAR2 (255)  NOT NULL ,
gene            VARCHAR2 (255)  NOT NULL ,
target\_sequence VARCHAR2 (255) ,
pert\_type       VARCHAR2 (255) ,
control\_type    VARCHAR2 (255) ,
smiles          VARCHAR2 (255)
)
;

ALTER TABLE P2T
ADD CONSTRAINT P2T\_PK PRIMARY KEY ( broad\_sample, perturbagen, gene ) ;

CREATE TABLE Perturbagen
(
metadata\_jcp2022          VARCHAR2 (255)  NOT NULL ,
well\_id                   VARCHAR2 (255)  NOT NULL ,
perturbagen               VARCHAR2 (255)  NOT NULL ,
metadata\_symbol           VARCHAR2 (255) ,
metadata\_ncbi\_gene\_id     VARCHAR2 (255) ,
metadata\_inchi            VARCHAR2 (255) ,
metadata\_inchikey         VARCHAR2 (255) ,
metadata\_smiles           VARCHAR2 (255) ,
metadata\_broad\_sample     VARCHAR2 (255) ,
metadata\_name             VARCHAR2 (255) ,
metadata\_vector           VARCHAR2 (255) ,
metadata\_prot\_match       FLOAT ,
metadata\_insert\_length    INTEGER ,
metadata\_taxon\_id         VARCHAR2 (255) ,
metadata\_transcript       VARCHAR2 (255) ,
metadata\_gene\_description VARCHAR2 (255)
)
;

ALTER TABLE Perturbagen
ADD CONSTRAINT Perturbagen\_PK PRIMARY KEY ( metadata\_jcp2022 ) ;

CREATE TABLE perturbagen\_target\_link
(
perturbation\_type VARCHAR2 (255)  NOT NULL ,
metadata\_jcp2022  VARCHAR2 (255)  NOT NULL ,
cell\_line\_type    VARCHAR2 (255)  NOT NULL ,
metadata\_plate    VARCHAR2 (255)  NOT NULL ,
P2T\_broad\_sample  VARCHAR2 (255)  NOT NULL ,
P2T\_perturbogen   VARCHAR2 (255)  NOT NULL ,
P2T\_gene          VARCHAR2 (255)  NOT NULL
)
;

CREATE TABLE perturbation\_matching
(
perturbation\_type             VARCHAR2 (255)  NOT NULL ,
gene\_compound                 VARCHAR2 (255)  NOT NULL ,
match                         VARCHAR2 (255)  NOT NULL ,
gene\_compound\_image           VARCHAR2 (255) ,
match\_image                   VARCHAR2 (255) ,
perturbation\_match\_similarity FLOAT ,
match\_resources               VARCHAR2 (255) ,
jcp2022\_id                    VARCHAR2 (255)  NOT NULL ,
match\_jcp2022\_id              VARCHAR2 (255) ,
phenotypic\_activity           FLOAT ,
phenotypic\_activity\_match     FLOAT
)
;

ALTER TABLE perturbation\_matching
ADD CONSTRAINT perturbation\_matching\_pk PRIMARY KEY ( gene\_compound, match, jcp2022\_id ) ;

CREATE TABLE perturbation\_matching\_link
(
perturbation\_type     VARCHAR2 (255)  NOT NULL ,
jcp2022\_id            VARCHAR2 (255)  NOT NULL ,
metadata\_inchi        VARCHAR2 (255) ,
metadata\_ncbi\_gene\_id VARCHAR2 (255) ,
P2T\_broad\_sample      VARCHAR2 (255)  NOT NULL ,
P2T\_perturbogen       VARCHAR2 (255)  NOT NULL ,
P2T\_gene              VARCHAR2 (255)  NOT NULL
)
;

CREATE TABLE Perturbation\_Target
(
gene            VARCHAR2 (255)  NOT NULL ,
target\_sequence VARCHAR2 (255)  NOT NULL ,
metadata\_plate  VARCHAR2 (255)  NOT NULL ,
metadata\_well   VARCHAR2 (255)
)
;

ALTER TABLE Perturbation\_Target
ADD CONSTRAINT Perturbation\_Target\_PK PRIMARY KEY ( gene, target\_sequence ) ;

CREATE TABLE Plate
(
plate\_name            VARCHAR2 (255)  NOT NULL ,
batch\_name            VARCHAR2 (255)  NOT NULL ,
plate\_description     VARCHAR2 (255) ,
assay\_plate\_barcode   VARCHAR2 (255)  NOT NULL ,
timepoint             VARCHAR2 (255) ,
perturbogen           VARCHAR2 (255) ,
pert\_type             VARCHAR2 (255) ,
pert\_time             VARCHAR2 (255) ,
control\_type          VARCHAR2 (255) ,
cell\_type             VARCHAR2 (255) ,
percent\_replicating   FLOAT ,
feature\_set           VARCHAR2 (255) ,
batch                 VARCHAR2 (255) ,
WELL\_metadata\_jcp2022 VARCHAR2 (255)  NOT NULL
)
;

ALTER TABLE Plate
ADD CONSTRAINT Plate\_PK PRIMARY KEY ( assay\_plate\_barcode, plate\_name ) ;

CREATE TABLE WELL
(
metadata\_source                     VARCHAR2 (255) ,
plate\_name                          VARCHAR2 (255)  NOT NULL ,
metadata\_well                       VARCHAR2 (255) ,
metadata\_jcp2022                    VARCHAR2 (255)  NOT NULL ,
compound\_metadata\_jcp2022           VARCHAR2 (255)  NOT NULL ,
crispr\_metadata\_jcp2022             VARCHAR2 (255)  NOT NULL ,
orf\_metadata\_jcp2022                VARCHAR2 (255)  NOT NULL ,
perturbogen                         VARCHAR2 (255)  NOT NULL ,
Perturbation\_Target\_gene            VARCHAR2 (255)  NOT NULL ,
Perturbation\_Target\_target\_sequence VARCHAR2 (255)  NOT NULL
)
;

ALTER TABLE WELL
ADD CONSTRAINT WELL\_PK PRIMARY KEY ( metadata\_jcp2022 ) ;

ALTER TABLE Batch
ADD CONSTRAINT Batch\_Plate\_FK FOREIGN KEY
(
Plate\_assay\_plate\_barcode,
Plate\_plate\_name
)
REFERENCES Plate
(
assay\_plate\_barcode,
plate\_name
)
;

ALTER TABLE feature\_rankings\_link
ADD CONSTRAINT feature\_rankings\_link\_P2T\_FK FOREIGN KEY
(
P2T\_broad\_sample,
P2T\_perturbogen,
P2T\_gene
)
REFERENCES P2T
(
broad\_sample,
perturbagen,
gene
)
;

ALTER TABLE Experiment
ADD CONSTRAINT fk\_experiment\_batch FOREIGN KEY
(
experiment\_id
)
REFERENCES Batch
(
batch\_name
)
;

ALTER TABLE feature\_rankings\_link
ADD CONSTRAINT fk\_feature\_rankings\_link\_feature\_rankings FOREIGN KEY
(
metadata\_ncbi\_gene\_id,
jcp2022\_id,
metadata\_inchi
)
REFERENCES feature\_rankings
(
feature,
jcp2022\_id,
gene\_compound
)
;

ALTER TABLE perturbation\_matching\_link
ADD CONSTRAINT fk\_perturbation\_matching\_link\_perturbation\_matching FOREIGN KEY
(
metadata\_inchi,
metadata\_ncbi\_gene\_id,
jcp2022\_id
)
REFERENCES perturbation\_matching
(
gene\_compound,
match,
jcp2022\_id
)
;

ALTER TABLE P2P\_Perturbagen\_link
ADD CONSTRAINT P2P\_Perturbogen\_P2P\_FK FOREIGN KEY
(
comparison\_type,
modality1
)
REFERENCES P2P
(
comparison\_type,
modality1
)
;

ALTER TABLE P2P\_Perturbagen\_link
ADD CONSTRAINT P2P\_Perturbogen\_Perturbogen\_FK FOREIGN KEY
(
Perturbagen\_metadata\_jcp2022
)
REFERENCES Perturbagen
(
metadata\_jcp2022
)
;

ALTER TABLE perturbagen\_target\_link
ADD CONSTRAINT perturbagen\_target\_link\_P2T\_FK FOREIGN KEY
(
P2T\_broad\_sample,
P2T\_perturbogen,
P2T\_gene
)
REFERENCES P2T
(
broad\_sample,
perturbagen,
gene
)
;

ALTER TABLE perturbation\_matching\_link
ADD CONSTRAINT perturbation\_matching\_link\_P2T\_FK FOREIGN KEY
(
P2T\_broad\_sample,
P2T\_perturbogen,
P2T\_gene
)
REFERENCES P2T
(
broad\_sample,
perturbagen,
gene
)
;

ALTER TABLE perturbagen\_target\_link
ADD CONSTRAINT perturbogen\_target\_link\_perturbation\_target\_fk FOREIGN KEY
(
cell\_line\_type,
metadata\_plate
)
REFERENCES Perturbation\_Target
(
gene,
target\_sequence
)
;

ALTER TABLE perturbagen\_target\_link
ADD CONSTRAINT perturbogen\_target\_link\_perturbogen\_fk FOREIGN KEY
(
metadata\_jcp2022
)
REFERENCES Perturbagen
(
metadata\_jcp2022
)
;

ALTER TABLE Plate
ADD CONSTRAINT Plate\_WELL\_FK FOREIGN KEY
(
WELL\_metadata\_jcp2022
)
REFERENCES WELL
(
metadata\_jcp2022
)
;

ALTER TABLE WELL
ADD CONSTRAINT WELL\_Perturbation\_Target\_FK FOREIGN KEY
(
Perturbation\_Target\_gene,
Perturbation\_Target\_target\_sequence
)
REFERENCES Perturbation\_Target
(
gene,
target\_sequence
)
;

ALTER TABLE WELL
ADD CONSTRAINT well\_perturbogen\_fk FOREIGN KEY
(
metadata\_jcp2022,
perturbogen
)
REFERENCES Perturbagen
(
metadata\_jcp2022
)
;

## -- Oracle SQL Developer Data Modeler Summary Report:

\-- CREATE TABLE                            14
\-- CREATE INDEX                             0
\-- ALTER TABLE                             25
\-- CREATE VIEW                              0
\-- ALTER VIEW                               0
\-- CREATE PACKAGE                           0
\-- CREATE PACKAGE BODY                      0
\-- CREATE PROCEDURE                         0
\-- CREATE FUNCTION                          0
\-- CREATE TRIGGER                           0
\-- ALTER TRIGGER                            0
\-- CREATE COLLECTION TYPE                   0
\-- CREATE STRUCTURED TYPE                   0
\-- CREATE STRUCTURED TYPE BODY              0
\-- CREATE CLUSTER                           0
\-- CREATE CONTEXT                           0
\-- CREATE DATABASE                          0
\-- CREATE DIMENSION                         0
\-- CREATE DIRECTORY                         0
\-- CREATE DISK GROUP                        0
\-- CREATE ROLE                              0
\-- CREATE ROLLBACK SEGMENT                  0
\-- CREATE SEQUENCE                          0
\-- CREATE MATERIALIZED VIEW                 0
\-- CREATE MATERIALIZED VIEW LOG             0
\-- CREATE SYNONYM                           0
\-- CREATE TABLESPACE                        0
\-- CREATE USER                              0
----------------------------------------------

\-- DROP TABLESPACE                          0
\-- DROP DATABASE                            0
----------------------------------------------

## -- REDACTION POLICY                         0

\-- ORDS DROP SCHEMA                         0
\-- ORDS ENABLE SCHEMA                       0
\-- ORDS ENABLE OBJECT                       0
----------------------------------------------

\-- ERRORS                                   0
\-- WARNINGS                                 0
