-- Mediated Schema (edited)

CREATE OR REPLACE VIEW G_BATCH AS
SELECT * FROM JCP.BATCH@jcp_link
;

CREATE OR REPLACE VIEW G_EXPERIMENT AS
SELECT * FROM JCP.EXPERIMENT@jcp_link
;

CREATE OR REPLACE VIEW G_FEATURE_RANKINGS AS
SELECT * FROM JCP.FEATURE_RANKINGS@jcp_link
;

CREATE OR REPLACE VIEW G_FEATURE_RANKINGS_LINK AS
SELECT * FROM JCP.FEATURE_RANKINGS_LINK@jcp_link
;

CREATE OR REPLACE VIEW G_JCP2PHARMA ( PERT_ID, PHARMA_CID, PHARMA_NAME ) AS
SELECT
    p.metadata_jcp2022 AS PERT_ID,
    r.CID              AS PHARMA_CID,
    r.DRUG_NAME        AS PHARMA_NAME
  FROM JCP.PERTURBAGEN@jcp_link p
  JOIN PHARMALCHEMY.R        r
    ON p.metadata_smiles = r.SMILES
;

CREATE OR REPLACE VIEW G_P2P AS
SELECT * FROM JCP.P2P@jcp_link
;

CREATE OR REPLACE VIEW G_P2P_PERTURBAGEN_LINK AS
SELECT * FROM JCP.P2P_Perturbagen_link@jcp_link
;

CREATE OR REPLACE VIEW G_P2T ( BROAD_SAMPLE, INCHIKEY, PERT_NAME, PUBCHEM_CID, PERTURBAGEN, GENE, TARGET_SEQUENCE, PERT_TYPE, CONTROL_TYPE, SMILES ) AS
SELECT
    broad_sample    AS BROAD_SAMPLE,
    inchikey        AS INCHIKEY,
    pert_name       AS PERT_NAME,
    pubchem_cid     AS PUBCHEM_CID,
    perturbagen     AS PERTURBAGEN,
    gene            AS GENE,
    target_sequence AS TARGET_SEQUENCE,
    pert_type       AS PERT_TYPE,
    control_type    AS CONTROL_TYPE,
    smiles          AS SMILES
  FROM JCP.P2T@jcp_link
;

CREATE OR REPLACE VIEW G_PERTURBAGEN ( PERT_ID, PERTURBAGEN_NAME, INCHI, INCHIKEY, SMILES ) AS
SELECT
    metadata_jcp2022  AS PERT_ID,
    perturbagen       AS PERTURBAGEN_NAME,
    metadata_inchi    AS INCHI,
    metadata_inchikey AS INCHIKEY,
    metadata_smiles   AS SMILES
  FROM JCP.PERTURBAGEN@jcp_link
;

CREATE OR REPLACE VIEW G_PERTURBATION_MATCHING AS
SELECT * FROM JCP.PERTURBATION_MATCHING@jcp_link
;

CREATE OR REPLACE VIEW G_PERTURBATION_MATCHING_LINK AS
SELECT * FROM JCP.PERTURBATION_MATCHING_LINK@jcp_link
;

CREATE OR REPLACE VIEW G_PLATE AS
SELECT * FROM JCP.PLATE@jcp_link
;

CREATE OR REPLACE VIEW G_R AS
SELECT * FROM PHARMALCHEMY.R
;

CREATE OR REPLACE VIEW G_R2G AS
SELECT * FROM PHARMALCHEMY.R2G
;

CREATE OR REPLACE VIEW G_WELL ( WELL_ID, PLATE_NAME, PERTURBAGEN, TARGET_GENE, TARGET_SEQUENCE ) AS
SELECT
    metadata_jcp2022                     AS WELL_ID,
    plate_name                           AS PLATE_NAME,
    perturbogen                          AS PERTURBAGEN,
    Perturbation_Target_gene             AS TARGET_GENE,
    Perturbation_Target_target_sequence  AS TARGET_SEQUENCE
  FROM JCP.WELL@jcp_link
;

CREATE OR REPLACE VIEW R_PERTURBAGEN_LINK AS
SELECT * FROM PHARMALCHEMY.R_Perturbagen_link
;

CREATE OR REPLACE VIEW R2G_PERTURBAGEN_LINK AS
SELECT * FROM PHARMALCHEMY.R2G_Perturbagen_link
;
